//-----------------------------------------------------
// Jarcas Promo Code System
// Copyright 2014 Jarcas Studios
//-----------------------------------------------------
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Collections;

public class JPCSSettingsWindow : EditorWindow {
	private readonly string runtimeSettingsPath = "Assets" + Path.DirectorySeparatorChar +
										   "JarcasPromoCodeSystem" + Path.DirectorySeparatorChar +
										   "Resources" + Path.DirectorySeparatorChar +
										   "JPCSRuntimeSettings.asset";
	private readonly string configPHPPath = "Assets" + Path.DirectorySeparatorChar +
											"JarcasPromoCodeSystem" + Path.DirectorySeparatorChar +
											"PHPServer" + Path.DirectorySeparatorChar +
											"config.php";

	[ MenuItem( "Window/Jarcas Promo Code System/Settings", false, 10 ) ]
	public static void ShowWindow( ) {
		EditorWindow.GetWindow( typeof( JPCSSettingsWindow ), true, "Jarcas Promo Code System Settings" );
	}


	private string serverURL;
	private string appID;
	private string jpcsPassword;
	private string salt;
	private string mySQLServer;
	private string mySQLUsername;
	private string mySQLPassword;
	private string mySQLDatabase;

	
	private void OnEnable( ) {
		// Get runtime setting from asset
		if ( string.IsNullOrEmpty( JPCSRuntimeSettings.instance.serverURL ) ) {
			// Default values
			serverURL = "http://www.yourdomain.com/promocodes/";
			appID = "com.your_company.your_product_name";
			salt = "aDAuLuv8mJoxK5gxyV3OKTtr3Wwl8ekh1p8i7sd1";
		} else {
			serverURL = JPCSRuntimeSettings.instance.serverURL;
			appID = JPCSRuntimeSettings.instance.appID;
			salt = JPCSRuntimeSettings.instance.salt;
		}

		// Get editor settings from EditorPrefs
		jpcsPassword = EditorPrefs.GetString( "jpcsPassword", "your_jpcs_password425364!DXT+" );
		mySQLServer = EditorPrefs.GetString( "mySQLServer", "mysql.yourdomain.com" );
		mySQLUsername = EditorPrefs.GetString( "mySQLUsername", "your_mysql_username" );
		mySQLPassword = EditorPrefs.GetString( "mySQLPassword", "your_mysql_password" );
		mySQLDatabase = EditorPrefs.GetString( "mySQLDatabase", "your_database_name" );
	}


	private void OnGUI( ) {
		serverURL = EditorGUILayout.TextField( new GUIContent( "PHP Server URL", "URL to the directory where the Jarcas Promo Code System PHP files are hosted" ), serverURL );
		appID = EditorGUILayout.TextField( new GUIContent( "App ID", "An identifier used to determine which codes were generated for use with which apps (e.g. - com.yourcompany.yourproductname). All codes are stored in one database, but List and Generate only deal with codes associated with this App ID." ), appID );
		jpcsPassword = EditorGUILayout.TextField( new GUIContent( "JPCS Admin Password", "Admin password for Jarcas Promo Code System. Needed to view, generate, or modify promo codes. No need to memorize this password, so a random string of characters (such as those generated by http://passwordsgenerator.net) is ideal." ), jpcsPassword );
		salt = EditorGUILayout.TextField( new GUIContent( "Salt", "A random 40 character string used to secure server messages against spoofing. You can generate a salt at http://passwordsgenerator.net" ), salt );
		mySQLServer = EditorGUILayout.TextField( new GUIContent( "mySQL Server", "Hostname where your mySQL server is hosted" ), mySQLServer );
		mySQLUsername = EditorGUILayout.TextField( new GUIContent( "mySQL Username", "Username to access your mySQL server" ), mySQLUsername );
		mySQLPassword = EditorGUILayout.TextField( new GUIContent( "mySQL Password", "Password to access your mySQL server" ), mySQLPassword );
		mySQLDatabase = EditorGUILayout.TextField( new GUIContent( "mySQL Database", "Name of the mySQL database that will be storing your promo codes" ), mySQLDatabase );

		// Save and close if the button is pressed
		if ( GUILayout.Button( "Save Settings" ) ) {
			// Create the asset on disk if it doesn't exist
			if ( !File.Exists( runtimeSettingsPath ) ) {
				AssetDatabase.CreateAsset( JPCSRuntimeSettings.instance, runtimeSettingsPath );
			}
			
			// Save the runtime settings to the asset
			JPCSRuntimeSettings.instance.serverURL = serverURL;
			JPCSRuntimeSettings.instance.appID = appID;
			JPCSRuntimeSettings.instance.salt = salt;

			EditorUtility.SetDirty( JPCSRuntimeSettings.instance );
			AssetDatabase.SaveAssets( );
			 
			// Save the editor/server only settings to EditorPrefs
			EditorPrefs.SetString( "jpcsPassword", jpcsPassword );
			EditorPrefs.SetString( "mySQLServer", mySQLServer );
			EditorPrefs.SetString( "mySQLUsername", mySQLUsername );
			EditorPrefs.SetString( "mySQLPassword", mySQLPassword );
			EditorPrefs.SetString( "mySQLDatabase", mySQLDatabase );

			// Save the server side settings to config.php
			GenerateConfigPHP( );

			// Message to user
			EditorUtility.DisplayDialog( "Settings saved!", "The config.php file in the PHPServer directory has been updated to reflect your settings. Be sure to upload config.php to your server to ensure proper operation.", "OK" );
			
			// Close this editor window
			Close( );
		}
	}


	private void GenerateConfigPHP( ) {
		string configText = "<?php\n";
		configText += "// Config file auto-generated by Jarcas Promo Code System for Unity\n";
		configText += "// Do not modify directly unless you know what you are doing\n";
		configText += "// Changes can be made by navigating in Unity to Window->Jarcas Promo Code System->Settings\n\n";
		configText += "$mysql_server = '" + mySQLServer + "';\n";
		configText += "$mysql_user = '" + mySQLUsername + "';\n";
		configText += "$mysql_password = '" + mySQLPassword + "';\n";
		configText += "$mysql_database = '" + mySQLDatabase + "';\n";
		configText += "$salt = '" + salt + "';\n";
		configText += "$jpcs_password = '" + jpcsPassword + "';\n";
		configText += "?>";
		File.WriteAllText( configPHPPath, configText );
	}
}
